package calculadoraios;

import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JSEF1
 */
public class iOS extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(iOS.class.getName());
    private boolean modoOscuro = false;
    private Calculadora miCalculadora = new Calculadora();

    private void activarModoClaro() {
        fondo.setIcon(new ImageIcon(getClass().getResource("/images/modoclaro.jpg")));
        toogle.setIcon(new ImageIcon(getClass().getResource("/images/moon.png")));
    }

    private void activarModoOscuro() {
        fondo.setIcon(new ImageIcon(getClass().getResource("/images/blakcmode.jpg")));
        toogle.setIcon(new ImageIcon(getClass().getResource("/images/sun.png")));
    }
    private String mostrarTiempo() {
        java.time.LocalTime ahora = java.time.LocalTime.now();
        return ahora.toString();    
       }

    /**
     * Creates new form iOS
     */
    public iOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delete = new javax.swing.JLabel();
        toogle = new javax.swing.JLabel();
        all_clear = new javax.swing.JLabel();
        percentaje = new javax.swing.JLabel();
        division = new javax.swing.JLabel();
        seven1 = new javax.swing.JLabel();
        eight = new javax.swing.JLabel();
        nine = new javax.swing.JLabel();
        multiplicacion1 = new javax.swing.JLabel();
        six = new javax.swing.JLabel();
        five = new javax.swing.JLabel();
        four = new javax.swing.JLabel();
        one = new javax.swing.JLabel();
        two = new javax.swing.JLabel();
        tree = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        equals = new javax.swing.JLabel();
        dot = new javax.swing.JLabel();
        zero = new javax.swing.JLabel();
        changear = new javax.swing.JLabel();
        history = new javax.swing.JLabel();
        substract = new javax.swing.JLabel();
        texto = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 50, 60));

        toogle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toogleMouseClicked(evt);
            }
        });
        getContentPane().add(toogle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 40, 30));

        all_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                all_clearMouseClicked(evt);
            }
        });
        getContentPane().add(all_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 50, 60));

        percentaje.setEnabled(false);
        percentaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                percentajeMouseClicked(evt);
            }
        });
        getContentPane().add(percentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 70, 60));

        division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisionMouseClicked(evt);
            }
        });
        getContentPane().add(division, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 70, 60));

        seven1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seven1MouseClicked(evt);
            }
        });
        getContentPane().add(seven1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 60, 60));

        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightMouseClicked(evt);
            }
        });
        getContentPane().add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 70, 60));

        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineMouseClicked(evt);
            }
        });
        getContentPane().add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 70, 60));

        multiplicacion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicacion1MouseClicked(evt);
            }
        });
        getContentPane().add(multiplicacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 80, 60));

        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixMouseClicked(evt);
            }
        });
        getContentPane().add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 70, 60));

        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveMouseClicked(evt);
            }
        });
        getContentPane().add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 70, 60));

        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourMouseClicked(evt);
            }
        });
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 70, 60));

        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMouseClicked(evt);
            }
        });
        getContentPane().add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 576, 80, 70));

        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoMouseClicked(evt);
            }
        });
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 80, 70));

        tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeMouseClicked(evt);
            }
        });
        getContentPane().add(tree, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 70, 70));

        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 80, 60));

        equals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equalsMouseClicked(evt);
            }
        });
        getContentPane().add(equals, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, 80, 70));

        dot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dotMouseClicked(evt);
            }
        });
        getContentPane().add(dot, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 670, 70, 60));

        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroMouseClicked(evt);
            }
        });
        getContentPane().add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 670, 60, 60));

        changear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changearMouseClicked(evt);
            }
        });
        getContentPane().add(changear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 80, 60));
        getContentPane().add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 40));

        substract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                substractMouseClicked(evt);
            }
        });
        getContentPane().add(substract, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 80, 60));

        texto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        texto.setBorder(null);
        texto.addActionListener(this::textoActionPerformed);
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 90));

        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 20));

        fondo.setBackground(new java.awt.Color(153, 153, 153));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blakcmode.jpg"))); // NOI18N
        fondo.setText("jLabel2");
        fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fondoMouseClicked(evt);
            }
        });
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
    String contenido = texto.getText();
    if (!contenido.isEmpty()) {
        // elimina el último numero 
        contenido = contenido.substring(0, contenido.length() - 1);
        //substring se encarga de coger cada letra de una cadena (un numero en este caso)
        texto.setText(contenido);
    }
    }//GEN-LAST:event_deleteMouseClicked

    private void toogleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toogleMouseClicked
       modoOscuro = !modoOscuro;

    if (modoOscuro) {
        activarModoOscuro();
    } else {
        activarModoClaro();
    }
    }//GEN-LAST:event_toogleMouseClicked

    private void all_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_all_clearMouseClicked
        texto.setText(""); 
        miCalculadora.limpiarHistorial();

    }//GEN-LAST:event_all_clearMouseClicked

    private void percentajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_percentajeMouseClicked
        // TODO add your handling code here:
        texto.setText(texto.getText() + "%");
    }//GEN-LAST:event_percentajeMouseClicked

    private void divisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseClicked
        texto.setText(texto.getText() + "÷");
    }//GEN-LAST:event_divisionMouseClicked

    private void seven1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seven1MouseClicked
        // TODO add your handling code here:
        texto.setText(texto.getText() + "7");
    }//GEN-LAST:event_seven1MouseClicked

    private void eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseClicked
        // TODO add your handling code here:
        texto.setText(texto.getText() + "8");
    }//GEN-LAST:event_eightMouseClicked

    private void nineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseClicked

        texto.setText(texto.getText() + "9");
    }//GEN-LAST:event_nineMouseClicked

    private void multiplicacion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicacion1MouseClicked

        texto.setText(texto.getText() + "x");
    }//GEN-LAST:event_multiplicacion1MouseClicked

    private void sixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseClicked
        // TODO add your handling code here:
        texto.setText(texto.getText() + "6");
    }//GEN-LAST:event_sixMouseClicked

    private void fiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseClicked
        // TODO add your handling code here:
        texto.setText(texto.getText() + "5");
    }//GEN-LAST:event_fiveMouseClicked

    private void fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseClicked
        // TODO add your handling code here:
        texto.setText(texto.getText() + "4");
    }//GEN-LAST:event_fourMouseClicked

    private void oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseClicked
        // TODO add your handling code here:
        texto.setText(texto.getText() + "1");
    }//GEN-LAST:event_oneMouseClicked

    private void twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseClicked
        // TODO add your handling code here:
        texto.setText(texto.getText() + "2");
    }//GEN-LAST:event_twoMouseClicked

    private void treeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMouseClicked
        // TODO add your handling code here:
        texto.setText(texto.getText() + "3");
    }//GEN-LAST:event_treeMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        texto.setText(texto.getText() + "+");
    }//GEN-LAST:event_addMouseClicked

    private void equalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalsMouseClicked
    String expresion = texto.getText();

        if (!expresion.isEmpty()) {
            try {
                double resultado = miCalculadora.evaluar(expresion);
                texto.setText(String.valueOf(resultado));
                
            } catch (ArithmeticException e) {
                texto.setText("Error: Div/0");
                e.printStackTrace();
            } catch (Exception e) {
                texto.setText("Error de sintaxis");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_equalsMouseClicked

    private void dotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotMouseClicked
         texto.setText(texto.getText() + ".");
    }//GEN-LAST:event_dotMouseClicked

    private void zeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseClicked
        // TODO add your handling code here:
        texto.setText(texto.getText() + "0");
    }//GEN-LAST:event_zeroMouseClicked

    private void changearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changearMouseClicked
        String contenido = texto.getText();
    if (!contenido.isEmpty()) {
        try {
            double valor = Double.parseDouble(contenido);
            valor *= -1;
            texto.setText(String.valueOf(valor));
        } catch (NumberFormatException e) {
            // Si el contenido no es un número válido, no hacemos nada o mostramos un mensaje
            System.out.println("No se puede cambiar el signo: entrada inválida");
        }
    }

    }//GEN-LAST:event_changearMouseClicked

    private void fondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fondoMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    jTextField1.setText(mostrarTiempo());
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void substractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substractMouseClicked
        // TODO add your handling code here:
        texto.setText(texto.getText() + "-");
    }//GEN-LAST:event_substractMouseClicked

    private void textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new iOS().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel all_clear;
    private javax.swing.JLabel changear;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel division;
    private javax.swing.JLabel dot;
    private javax.swing.JLabel eight;
    private javax.swing.JLabel equals;
    private javax.swing.JLabel five;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel four;
    private javax.swing.JLabel history;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel multiplicacion1;
    private javax.swing.JLabel nine;
    private javax.swing.JLabel one;
    private javax.swing.JLabel percentaje;
    private javax.swing.JLabel seven1;
    private javax.swing.JLabel six;
    private javax.swing.JLabel substract;
    private javax.swing.JTextField texto;
    private javax.swing.JLabel toogle;
    private javax.swing.JLabel tree;
    private javax.swing.JLabel two;
    private javax.swing.JLabel zero;
    // End of variables declaration//GEN-END:variables
}
